#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "Usage: $0 <version>"
  echo latest tag: $(git describe --tags --abbrev=0)
  exit 1
fi

# replace ghcr.io/progsoftware/dcd:VERSION in README.md

version=$1
sed -i '' 's#ghcr.io/progsoftware/dcd:v[0-9.]*#ghcr.io/progsoftware/dcd:'$version'#g' README.md
git commit -m "Update README.md" README.md
git push
git tag $version
git push --tags
